### ISSUE TITLE
Add Attribution for ALL Assets in credits popup

### ISSUE THREAD

**Issue by ThomasChr** [ang-vil/angvil#42]
I've used the jump sound from: https://www.kenney.nl
The license does not require us to do so, however we should appreciate his work!

>License: (CC0 1.0 Universal) You're free to use these game assets in any project, personal or commercial. There's no need to ask permission before using these. Giving attribution is not required, but is greatly appreciated!

**Comment by burned42** [comment]
Those links in the credits should also be clickable IMHO

**Comment by ThomasChr** [comment]
Oh no! The jump sound is not from Kenny, it's from here: 
https://opengameart.org/content/platformer-jumping-sounds

CC-BY 3.0:
> If you do use this, all I ask is that you credit me as dklon somewhere.

**Comment by ThomasChr** [comment]
We need two new sound atributions:
https://opengameart.org/content/bad-sound-1
https://opengameart.org/content/energy-drain
See #45

**Comment by ThomasChr** [comment]
I also added a game over sound. CC0:
https://opengameart.org/content/game-over-soundold-school
