### ISSUE TITLE
Level name is cut of on small screens

### ISSUE THREAD

**Issue by ThomasChr** [ang-vil/angvil#64]
on my smartphone:
![C1319949-E27C-4682-BD2C-406660A30AF5](https://user-images.githubusercontent.com/13014163/151711518-8ce6a25d-2557-4ccc-950e-ff7b0ab1cdfc.jpeg)

**Comment by burned42** [comment]
That's that scroll bar issue again like we had in multiple places already, so making the size of that node a bit bigger should solve the issue.

**Comment by ThomasChr** [comment]
fixed!
